services:
  mongodb:
    image: mongo:7
    container_name: openslo-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    image: sanjuthomas/open-slo-repository:latest
    build: .
    container_name: openslo-repository
    ports:
      - "9090:9090"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/openslo
    depends_on:
      - mongodb

volumes:
  mongodb_data:
