spring.application.name=open-slo-repository

server.port=9090

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/openslo

# Basic auth (default credentials for development)
openslo.security.username=openslo
openslo.security.password=openslo123

spring.jackson.serialization.indent-output=true
